### ISSUE TITLE
项目运行 404 的问题

### ISSUE THREAD

**Issue by ericclose** [dengweiping4j/PPA#1]
您好，能请问一下这个问题怎么解决吗 :smile:
![2020-06-09_16-06](https://user-images.githubusercontent.com/34526560/84122850-a41fee00-aa6b-11ea-8903-ca61cbb2f2bb.png)

**Comment by 2280065582shi** [comment]
密码是什么呀，登不上去，救救孩子

**Comment by 2280065582shi** [comment]
我也是，你现在改了没
